### ISSUE TITLE
we clone this repository,and run shows error

### ISSUE THREAD

**Issue by adminSxs** [Ameobea/rust-cloud-run-demo#1]
Error: Database configuration failure: 'rocket_app'
    => Error: A table named `databases` was not found for this configuration
Error: Rocket failed to launch due to failing fairings:
    => 'rocket_app' Database Pool

**Comment by Ameobea** [comment]
Hi!  I'm not sure, but it looks like you're trying to run migrations before you've set up diesel on the database.

Make sure that you've run `diesel setup` and set the `DATABASE_URL` environment variable to reflect your database's URL.

Check out the official guide for additional help: http://diesel.rs/guides/getting-started/

**Comment by adminSxs** [comment]
> Hi! I'm not sure, but it looks like you're trying to run migrations before you've set up diesel on the database.
> 
> Make sure that you've run `diesel setup` and set the `DATABASE_URL` environment variable to reflect your database's URL.
> 
> Check out the official guide for additional help: http://diesel.rs/guides/getting-started/

I has resolved,add a ROCKET_DATABASES environment. thanks your reply
